"""empty message

Revision ID: 140f0dc9c53f
Revises: 762402052503
Create Date: 2021-04-01 00:05:01.589712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140f0dc9c53f'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
